Topic/edantec kinematics
Simple-Robotics/aligator pull request #131
Opened 2024-03-11 10:24 UTC by edantec

This PR aims at adding a kinodynamics forward scheme to Aligator. This kinodynamics scheme takes into account the full kinematics of the robot and its centroidal dynamics expressed in base frame. The derivatives are easier to compute than the full dynamics ones, at the price of having to rely on an inverse dynamics QP to output the commanded torques. 

A Python script of an optimal control problem involving Solo walking is provided as an example.

2024-03-12 11:19 UTC, jcarpent requested changes
Thanks @edantec for these nice contributions.
I provide minor comments.

Overall, the computational efficiency can be improved but it can wait.

2024-03-12 11:19 UTC, jcarpent commented on include/aligator/modelling/dynamics/kinodynamics-fwd.hxx
> +  d.Jx_.block(pin_model_.nv, 0, 6, pin_model_.nv) -= d.Agu_inv_ * d.dhdot_dq_;
Use noalias when doing such computations:
```suggestion
  d.Jx_.block(pin_model_.nv, 0, 6, pin_model_.nv).noalias() -= d.Agu_inv_ * d.dhdot_dq_;
```

2024-03-12 11:19 UTC, jcarpent commented on include/aligator/modelling/dynamics/kinodynamics-fwd.hxx
> +  d.Jx_.block(pin_model_.nv, 0, 6, pin_model_.nv) -= d.Agu_inv_ * d.dhdot_dq_;
same here

2024-03-12 11:19 UTC, jcarpent commented on include/aligator/modelling/dynamics/kinodynamics-fwd.hxx
> +  d.Jx_.block(pin_model_.nv, pin_model_.nv, 6, pin_model_.nv) =
same here

2024-03-21 15:50 UTC, ManifoldFR commented
@jcarpent do you still need to reviesw this PR?

2024-03-25 17:16 UTC, merged